### ISSUE TITLE
Problem links here

### ISSUE THREAD

**Issue by Chaitya62** [KJSCE-Codecell/standard-library-in-x#16]
Add the problems here in the following format 
Problem Link:
Topics: 
Other Concepts: if any

**Comment by inishchith** [comment]
Problem Link : https://www.codechef.com/JUNE17/problems/UNIONSET
Topic : set_union

**Comment by jaykanakiya** [comment]
Problem Link: https://www.codechef.com/problems/VCS
Topic: Vectors, Maps
