### ISSUE TITLE
Start working on subtopics

### ISSUE THREAD

**Issue by Chaitya62** [KJSCE-Codecell/standard-library-in-x#2]
Pick a topic and  start making a different readme for it and link it to the main index.
Comment what you are working on below

**Comment by inishchith** [comment]
i'll work on queues and sets .

**Comment by nurdtechie98** [comment]
I'll do vectors pairs and stack by evening

**Comment by Ankit-22** [comment]
I am starting maps..

**Comment by cipherhacker** [comment]
All the built-in functions

**Comment by Chaitya62** [comment]
Introduction

**Comment by nurdtechie98** [comment]
I'll do Stack and bitset tonight

**Comment by inishchith** [comment]
Anything remaining to cover ? @Chaitya62

**Comment by inishchith** [comment]
i think problem section should be added to every subtopic that we're working on instead of it being in README.md .

**Comment by nurdtechie98** [comment]
Yes Noted
