### ISSUE TITLE
Linking Issue in Gh-pages

### ISSUE THREAD

**Issue by Chaitya62** [KJSCE-Codecell/standard-library-in-x#34]
The new theme I have selected seems like a good fit for our documentation but there are some issues.
Let's say we have two sub-headings with same name than the link that is generated by gh-pages for navigation links to the first sub-heading. 
To understand the bug clearly click on both the introduction tabs [here](http://kjscecodecell.com/Cpp-STL-Notes/containers/maps.html)

**Comment by Chaitya62** [comment]
I have done a temporary fix [here](http://kjscecodecell.com/Cpp-STL-Notes/Pairs&Tuples.html) basically  for first introduction the code is ```<h2>Introduction</h2>``` for second it is ```<h2> Introduction</h2>``` notice the space after h2 in the second introduction heading

**Comment by inishchith** [comment]
Oh . i'll work on this .

**Comment by inishchith** [comment]
i tried working on maps.md by characterising them on the basis of leading and trailing spaces (fix mentioned @Chaitya62 's comment ). it works fine . so i can't find a better way to do this . for now i think we can go ahead with this . i'll push changes after fixing every .md with this problem . 
check [here](http://nishchith.me/Cpp-STL-Notes/containers/maps.html) for now .

**Comment by Chaitya62** [comment]
Ya, it's fine as long as it doesn't have a side effect
