### ISSUE TITLE
Python Adds

### ISSUE THREAD

**Issue by inishchith** [KJSCE-Codecell/standard-library-in-x#45]
### Advanced

- heapq 
    - heapify()
    - heappush()
    - heapop()
    - heappushpop()
    - heapreplace()
    - nlargest()
    - nsmallest()

- bisect 
     - bisect()
     - bisect_left()
     - bisect_right()
     - insort()
     - insort_left()
     - insort_right()
- itertools
     - accumulate()
     - combinations()
     - combinations_with_replacement()
     - count()
     - permutations()
- counter 
     - Counter()
     - most_common()
     - elements()
     - update()

- built-in functions

**Comment by nilshah98** [comment]
- Sets
  - Mutable / Immutable
  - Creating
  - Adding
    - add()
    - update()
  - Removing
    - remove()
    - discard()
  - Iterating
    - for i in _setname_
  - Copying
    - copy()
  - Inclusion / Exclusion
    - x in _setname_
    - x not in _setname_
  - Union
    - union()
  - Intersection
    - intersection()
  - Difference
    - difference()
  - Superset
    - issuperset()
  - Subset
    - issubset()
  - Symettric Difference
    - symettric_difference()
  - Sorting
    - sorted(_setname_)
    - _returns list though_
   - _why is set unsorted? hashing ..._
  - Length
    - len(_setname_)

- Lists
  - Mutable / Immutable
  - Creating
  - Adding
    - append()
    - extend()
    - _listname_ + [1,2,3]
    - insert()
  - Removing
    - del
    - remove()
    - pop()
  - Iterating
    - for i in _listname_
    - for i in range(len(_listname_))
  - Accessing
    - _listname_[index]
  - Copying
    - _listname_[::]
    - copy
  - Counting
    - count()
  - Index of element
    - index()
  - Slicing
    - _listname_[ start : end : step ]
  - Sorting
    - sorted
    - sort()
  - Length
    - len(_listname_)

- Dictionary
  - Mutable / Immutable
  - Constraints on key:value pair
    - key **must be** immutable
  - Creation
  - Adding key:value pair
    - _dictname_[key] = value
    - **NOTE**: Will override earlier value
  - Updating key:value pair
    - check if key present in dict, if yes then use temp and or adding techniques
  - Removing key:value pair
    - del _dictname_[key]
    - pop()
  - Iterating
    - iterate through the keys, and access value
  - Accessing
    - _dictname_[key]
    - keys()
    - items()
  - Sorting
    - copy the list of keys, in a set, and sort the set, which returns a list, iterate through the sorted list and access key:value pairs
  - Length
    - len(_dictname_)
