### ISSUE TITLE
Python Dictionary

### ISSUE THREAD

**Issue by nilshah98** [KJSCE-Codecell/standard-library-in-x#51]
Dictionary
 - [x] dictname[key] = value
 - [x] NOTE: Will override earlier value
 - [ ] check if key present in dict, if yes then use temp and or adding techniques
 - [x] del dictname[key]
 - [x] pop()
 - [ ] iterate through the keys, and access value
 - [x] dictname[key]
 - [x] keys()
 - [x] items()
 - [x] copy the list of keys, in a set, and sort the set, which returns a list, iterate through the sorted list and access key:value pairs
 - [x] len(dictname)

**Comment by inishchith** [comment]
these are just sufficient imo
