### ISSUE TITLE
JAVA Iterators & Essential Methods

### ISSUE THREAD

**Issue by Kadam-Tushar** [KJSCE-Codecell/standard-library-in-x#61]
- Iterators
     - [X] iterator()
     - [X] listIterator()
     - [X] for each style
- Essential Methods
     - [X] Comparator
        - [X] comparable,compareTo(), compare()
     - [X] equals(), hashCode(), toString()
     - [X] size()
     - [X] isEmpty()
     - [X] pollFirst() & pollLast()
     - [X] poll()

**Comment by inishchith** [comment]
@Kadam-Tushar an additional task would be to monitor all the `java` issues and check if something is left to add 😄

**Comment by Kadam-Tushar** [comment]
Okay !
